CREATE TABLE PRODUTO (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	descricao VARCHAR(100),
	preco NUMERIC,
	qtde_estoque INTEGER,
	tipo VARCHAR(20)	
);


INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTDE_ESTOQUE,TIPO) VALUES ('Notebook','Última geração',5000.00,5,'PRODUTO');
INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTDE_ESTOQUE,TIPO) VALUES ('Café','Extra forte',200.00,100,'PRODUTO');
INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTDE_ESTOQUE,TIPO) VALUES ('Limpeza Notebook','limpeza das boas',100.00,1,'SERVICO');
INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTDE_ESTOQUE,TIPO) VALUES ('Entrega','mais rápida possível',500.00,1,'SERVICO');